### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by dschaf** [MefawYT/offsets#1]
how did u manage to get these ive been trying to find a way to get offsets for a very very long time and its all thats left in my skillset for sd accept for pattern scanning ive seen faint videos before with cheat engine dll that supposedly bypasses eac while inspecting the game with a debugger i just need help with this hope u can help

**Comment by 700montes** [comment]
he got those by pasting a public dumper. github.com/dano20zombie/FortUpdater.
you can just modify the dumper so it would dump all the game's objects and it's offset, not really hard.
it's better to do that as you won't spend 294 hours reversing every update.

**Comment by Mefaw1337** [comment]
i updated now there is all fortnite offsets :) . Maybe gonna release my custom dumper soon
