### ISSUE TITLE
could u teach me how to pull offsets?

### ISSUE THREAD

**Issue by dschaf** [MefawYT/offsets#3]
all i know how to pull is uworld sense i have the pattern already

i dont know how to get them for like playerstate and the rest

**Comment by Mefaw1337** [comment]
Hey , here is the code to put the offsets
https://github.com/pulslol/Neutron.gg-Soruce/blob/main/offsets.h
and 
https://github.com/pulslol/Neutron.gg-Soruce/blob/main/offsets.cpp
