### ISSUE TITLE
New Offsets For Fortnite Update :)

### ISSUE THREAD

**Issue by Kaelemm** [MefawYT/offsets#6]
Hello its me again, do you think you could get the new offsets? Fortnite had an update again. If you can i would appreciate that so much :)

**Comment by MefawYT** [comment]
> Hello its me again, do you think you could get the new offsets? Fortnite had an update again. If you can i would appreciate that so much :)

Yes , im not home rn updating in 3hours

**Comment by Kaelemm** [comment]
Ok, thank you so much!
