### ISSUE TITLE
Hello Again! :) New fortnite update.

### ISSUE THREAD

**Issue by Kaelemm** [MefawYT/offsets#7]
Do you think you could dump the new offsets for the fortnite update :)

**Comment by MefawYT** [comment]
idk its harder now

**Comment by homeless1337** [comment]
no lmao

**Comment by furiosdestruct** [comment]
bruh

**Comment by MefawYT** [comment]
Everyone searching for patterns  and 0 cheat works thats why apple just came out yesterday like this people gonna buy apple

**Comment by homeless1337** [comment]
i have the all the sigs lmao

**Comment by MefawYT** [comment]
> i have the all the sigs lmao

Send lmao

**Comment by MefawYT** [comment]
updated
